<?php

namespace NewsletterBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNEWSdql($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT n FROM NewsletterBundle:Newsletter n WHERE n.id=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

}
