<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateenable($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('AppBundle:User', 'p')
            ->set('p.enabled', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "1")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }

    public function updatedisable($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('AppBundle:User', 'p')
            ->set('p.enabled', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "0")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }
}
