esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /produit

module_devis:
    resource: "@ModuleDevisBundle/Resources/config/routing.yml"
    prefix:   /

point_collect:
    resource: "@PointCollectBundle/Resources/config/routing.yml"
    prefix:   /

newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /newsletter

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /connect/check-facebook

googleplus_login:
    path: /connect/check-google
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }


