<?php

namespace EventBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByuser($user,$event)
    {

        $qb = $this->createQueryBuilder('s');
        $qb->where('s.User=:user')
            ->andWhere('s.Event=:event')

            ->setParameter('user', $user)
            ->setParameter('event', $event);

        return $qb->getQuery()->getResult();

    }
}
