<?php

namespace EventBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    public function Number($eventID)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT (e) as nb FROM EventBundle:Wishlist e where e.Event=:event");
        $query->setParameter('event',$eventID);

        return $query->getSingleScalarResult();

    }

    public function findByuser($user,$event)
    {

        $qb = $this->createQueryBuilder('s');
        $qb->where('s.User=:user')
            ->andWhere('s.Event=:event')

            ->setParameter('user', $user)
            ->setParameter('event', $event);

        return $qb->getQuery()->getResult();

    }

}
