<?php

namespace BlogBundle\Repository;

/**
 * CategorieBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
