<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function update($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('BlogBundle:Post', 'p')
            ->set('p.publier', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "1")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }

    public function categorie($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->join('a.CategorieBlog_id', 'c')
            ->where($qb->expr()->in('c.id', $id));

        return $qb->getQuery()
            ->getResult();

    }


    public function OrderByMeilleur(){

        $qb=$this->CreateQueryBuilder('s');
        $qb->where('s.publier =?1')
            ->setParameter(1, "1");



        $qb->orderBy('s.nombrevue', 'DESC');
        $qb->setMaxResults(3);
        return $qb->getQuery()->getResult();


    }

    public function updatepublie($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('BlogBundle:Post', 'p')
            ->set('p.publier', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "1")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }

    public function updatenonpublie($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('BlogBundle:Post', 'p')
            ->set('p.publier', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "0")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }


    public function findBySlug($id)
    {
        $qb=$this->createQueryBuilder('s');
        $qb->where('s.slug=:slug')->setParameter('slug',$id);
        return $qb->getQuery()->getSingleResult();
    }

}
