<?php

namespace ProductBundle\Repository;

/**
 * Produit2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit2Repository extends \Doctrine\ORM\EntityRepository
{

    public function update($id)
    {

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('ProductBundle:Produit2', 'p')
            ->set('p.publie', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, "1")
            ->setParameter(2, $id)

            ->getQuery();
        return $q->getResult();
    }

    public function findByPublie()
    {

        $qb = $this->createQueryBuilder('s');
        $qb->where('s.publie=:pub')

            ->setParameter('pub', 1);

        return $qb->getQuery()->getResult();

    }

    public function OrderByPrixDesc(){

        $qb=$this->CreateQueryBuilder('s');
        $qb->where('s.publie=:pub')

            ->setParameter('pub', 1);


        $qb->orderBy('s.Prix', 'DESC');
        return $qb->getQuery()->getResult();


    }

    public function OrderByPrixAsc(){

        $qb=$this->CreateQueryBuilder('s');
        $qb->where('s.publie=:pub')

            ->setParameter('pub', 1);


        $qb->orderBy('s.Prix');
        return $qb->getQuery()->getResult();


    }
}
