<?php

namespace ProductBundle\Repository;

/**
 * WishlistProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
