event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }
event_homepageadmin:
    path:     /admin/
    defaults: { _controller: EventBundle:Default:indexadmin }
event_ajoutevenement:
    path:     /ajout
    defaults: { _controller: EventBundle:Event:AjoutEvenement }
event_ajoutevenementAdmin:
    path:     /admin/ajoutAdmin
    defaults: { _controller: EventBundle:Event:AjoutEvenementAdmin }
event_afficheeventadmin:
    path:     /admin/afficheevent
    defaults: { _controller: EventBundle:Event:AfficheEvenement2 }
event_updateeventadmin:
    path:     /admin/updateevent/{id}
    defaults: { _controller: EventBundle:Event:UpdateEvenementAdmin }
event_afficheeventNtadmin:
    path:     /admin/afficheeventnontraiter
    defaults: { _controller: EventBundle:Event:AfficheEvenementNonTraiter }
event_deleteeventadmin:
    path:     /admin/deleteevent/{id}
    defaults: { _controller: EventBundle:Event:deleteEvenement }
croissant:
    path:     /croissant
    defaults: { _controller: EventBundle:Event:Orderprixasc }
decroissant:
    path:     /decroissant
    defaults: { _controller: EventBundle:Event:Orderprixdesc }
date:
    path:     /date
    defaults: { _controller: EventBundle:Event:Orderdate }
meilleur:
    path:     /meilleur
    defaults: { _controller: EventBundle:Event:Ordermeuilleur }
event_afficheeventuser:
    path:     /listeevenements
    defaults: { _controller: EventBundle:Event:AfficheEvenement }
detailsevent:
    path:     /eventdetails/{id}
    defaults: { _controller: EventBundle:Event:detailEvenement }
event_getevent:
    path:     /getevent
    defaults: { _controller: EventBundle:Event:getEvenements }
event_showing10:
    path:     /showing10
    defaults: { _controller: EventBundle:Event:showing10 }
event_getevent14:
    path:     /showing14
    defaults: { _controller: EventBundle:Event:showing14 }
event_getevent18:
    path:     /showing18
    defaults: { _controller: EventBundle:Event:showing18 }
Participer:
    path:     /participer
    defaults: { _controller: EventBundle:Event:particper }
Wishlist:
    path:     /wishlist
    defaults: { _controller: EventBundle:Event:wishlist }
afficheWishlist:
    path:     /affichewishlist
    defaults: { _controller: EventBundle:Event:affichewishlist }
deleteWishlist:
    path:     /deletewishlist/{id}
    defaults: { _controller: EventBundle:Event:deleteWishlist }
deleteeventuser:
    path:     /deletemyevent/{id}
    defaults: { _controller: EventBundle:Event:deleteEvenementUser }
affichemesevenements:
    path:     /mesevenements
    defaults: { _controller: EventBundle:Event:AfficheMesEvenements }
event_updateevent:
    path:     /updateevent/{id}
    defaults: { _controller: EventBundle:Event:UpdateEvenement }
traiteruserenable:
    path:     /etatenable/{id}
    defaults: { _controller: EventBundle:Event:traiteruserEnable }
traiteruserdisable:
    path:     /etatdisable/{id}
    defaults: { _controller: EventBundle:Event:traiteruserdisable }
deleteuser:
    path:         /admin/deleteuser/{id}
    defaults: { _controller: EventBundle:Event:deleteuser }
afficheuser:
    path:     /admin/users
    defaults: { _controller: EventBundle:Event:Afficheuser }
traitereventpublie:
    path:     /etatpublie/{id}
    defaults: { _controller: EventBundle:Event:traiterEvenementpublie }
traitereventnonpublie:
    path:     /etatnonpublie/{id}
    defaults: { _controller: EventBundle:Event:traiterEvenementnonpublie }
